# Generated by Django 5.2.2 on 2026-05-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='credito',
            field=models.BooleanField(default=False),
        ),
    ]
