# Generated by Django for SI2 examen 2026 - Ejercicio 3
# Anyade el campo credito (BooleanField) al modelo Pago.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='credito',
            field=models.BooleanField(default=False),
        ),
    ]
